// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.4
// source: proto/demo/payments/v1/payments.proto

package paymentsv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PaymentMethod int32

const (
	PaymentMethod_PAYMENT_METHOD_UNKNOWN PaymentMethod = 0
	PaymentMethod_PAYMENT_METHOD_CARD    PaymentMethod = 1
	PaymentMethod_PAYMENT_METHOD_SBP     PaymentMethod = 2
	PaymentMethod_PAYMENT_METHOD_CASH    PaymentMethod = 3
)

// Enum value maps for PaymentMethod.
var (
	PaymentMethod_name = map[int32]string{
		0: "PAYMENT_METHOD_UNKNOWN",
		1: "PAYMENT_METHOD_CARD",
		2: "PAYMENT_METHOD_SBP",
		3: "PAYMENT_METHOD_CASH",
	}
	PaymentMethod_value = map[string]int32{
		"PAYMENT_METHOD_UNKNOWN": 0,
		"PAYMENT_METHOD_CARD":    1,
		"PAYMENT_METHOD_SBP":     2,
		"PAYMENT_METHOD_CASH":    3,
	}
)

func (x PaymentMethod) Enum() *PaymentMethod {
	p := new(PaymentMethod)
	*p = x
	return p
}

func (x PaymentMethod) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (PaymentMethod) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_demo_payments_v1_payments_proto_enumTypes[0].Descriptor()
}

func (PaymentMethod) Type() protoreflect.EnumType {
	return &file_proto_demo_payments_v1_payments_proto_enumTypes[0]
}

func (x PaymentMethod) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use PaymentMethod.Descriptor instead.
func (PaymentMethod) EnumDescriptor() ([]byte, []int) {
	return file_proto_demo_payments_v1_payments_proto_rawDescGZIP(), []int{0}
}

type CaptureType int32

const (
	CaptureType_CAPTURE_TYPE_UNKNOWN CaptureType = 0
	CaptureType_CAPTURE_TYPE_FULL    CaptureType = 1
	CaptureType_CAPTURE_TYPE_PARTIAL CaptureType = 2
)

// Enum value maps for CaptureType.
var (
	CaptureType_name = map[int32]string{
		0: "CAPTURE_TYPE_UNKNOWN",
		1: "CAPTURE_TYPE_FULL",
		2: "CAPTURE_TYPE_PARTIAL",
	}
	CaptureType_value = map[string]int32{
		"CAPTURE_TYPE_UNKNOWN": 0,
		"CAPTURE_TYPE_FULL":    1,
		"CAPTURE_TYPE_PARTIAL": 2,
	}
)

func (x CaptureType) Enum() *CaptureType {
	p := new(CaptureType)
	*p = x
	return p
}

func (x CaptureType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (CaptureType) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_demo_payments_v1_payments_proto_enumTypes[1].Descriptor()
}

func (CaptureType) Type() protoreflect.EnumType {
	return &file_proto_demo_payments_v1_payments_proto_enumTypes[1]
}

func (x CaptureType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use CaptureType.Descriptor instead.
func (CaptureType) EnumDescriptor() ([]byte, []int) {
	return file_proto_demo_payments_v1_payments_proto_rawDescGZIP(), []int{1}
}

type Money struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Units         int64                  `protobuf:"varint,1,opt,name=units,proto3" json:"units,omitempty"`
	Nanos         int32                  `protobuf:"varint,2,opt,name=nanos,proto3" json:"nanos,omitempty"`
	CurrencyCode  string                 `protobuf:"bytes,3,opt,name=currency_code,json=currencyCode,proto3" json:"currency_code,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Money) Reset() {
	*x = Money{}
	mi := &file_proto_demo_payments_v1_payments_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Money) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Money) ProtoMessage() {}

func (x *Money) ProtoReflect() protoreflect.Message {
	mi := &file_proto_demo_payments_v1_payments_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Money.ProtoReflect.Descriptor instead.
func (*Money) Descriptor() ([]byte, []int) {
	return file_proto_demo_payments_v1_payments_proto_rawDescGZIP(), []int{0}
}

func (x *Money) GetUnits() int64 {
	if x != nil {
		return x.Units
	}
	return 0
}

func (x *Money) GetNanos() int32 {
	if x != nil {
		return x.Nanos
	}
	return 0
}

func (x *Money) GetCurrencyCode() string {
	if x != nil {
		return x.CurrencyCode
	}
	return ""
}

type Card struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PanLast4      string                 `protobuf:"bytes,1,opt,name=pan_last4,json=panLast4,proto3" json:"pan_last4,omitempty"`
	ExpMonth      int32                  `protobuf:"varint,2,opt,name=exp_month,json=expMonth,proto3" json:"exp_month,omitempty"`
	ExpYear       int32                  `protobuf:"varint,3,opt,name=exp_year,json=expYear,proto3" json:"exp_year,omitempty"`
	HolderName    string                 `protobuf:"bytes,4,opt,name=holder_name,json=holderName,proto3" json:"holder_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Card) Reset() {
	*x = Card{}
	mi := &file_proto_demo_payments_v1_payments_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Card) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Card) ProtoMessage() {}

func (x *Card) ProtoReflect() protoreflect.Message {
	mi := &file_proto_demo_payments_v1_payments_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Card.ProtoReflect.Descriptor instead.
func (*Card) Descriptor() ([]byte, []int) {
	return file_proto_demo_payments_v1_payments_proto_rawDescGZIP(), []int{1}
}

func (x *Card) GetPanLast4() string {
	if x != nil {
		return x.PanLast4
	}
	return ""
}

func (x *Card) GetExpMonth() int32 {
	if x != nil {
		return x.ExpMonth
	}
	return 0
}

func (x *Card) GetExpYear() int32 {
	if x != nil {
		return x.ExpYear
	}
	return 0
}

func (x *Card) GetHolderName() string {
	if x != nil {
		return x.HolderName
	}
	return ""
}

type AuthorizeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PaymentId     string                 `protobuf:"bytes,1,opt,name=payment_id,json=paymentId,proto3" json:"payment_id,omitempty"`
	OrderId       string                 `protobuf:"bytes,2,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	UserId        string                 `protobuf:"bytes,3,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Amount        *Money                 `protobuf:"bytes,4,opt,name=amount,proto3" json:"amount,omitempty"`
	Method        PaymentMethod          `protobuf:"varint,5,opt,name=method,proto3,enum=demo.payments.v1.PaymentMethod" json:"method,omitempty"`
	Card          *Card                  `protobuf:"bytes,6,opt,name=card,proto3" json:"card,omitempty"`
	MetadataKeys  []string               `protobuf:"bytes,7,rep,name=metadata_keys,json=metadataKeys,proto3" json:"metadata_keys,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AuthorizeRequest) Reset() {
	*x = AuthorizeRequest{}
	mi := &file_proto_demo_payments_v1_payments_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuthorizeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuthorizeRequest) ProtoMessage() {}

func (x *AuthorizeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_demo_payments_v1_payments_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuthorizeRequest.ProtoReflect.Descriptor instead.
func (*AuthorizeRequest) Descriptor() ([]byte, []int) {
	return file_proto_demo_payments_v1_payments_proto_rawDescGZIP(), []int{2}
}

func (x *AuthorizeRequest) GetPaymentId() string {
	if x != nil {
		return x.PaymentId
	}
	return ""
}

func (x *AuthorizeRequest) GetOrderId() string {
	if x != nil {
		return x.OrderId
	}
	return ""
}

func (x *AuthorizeRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *AuthorizeRequest) GetAmount() *Money {
	if x != nil {
		return x.Amount
	}
	return nil
}

func (x *AuthorizeRequest) GetMethod() PaymentMethod {
	if x != nil {
		return x.Method
	}
	return PaymentMethod_PAYMENT_METHOD_UNKNOWN
}

func (x *AuthorizeRequest) GetCard() *Card {
	if x != nil {
		return x.Card
	}
	return nil
}

func (x *AuthorizeRequest) GetMetadataKeys() []string {
	if x != nil {
		return x.MetadataKeys
	}
	return nil
}

type AuthorizeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        string                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	RequestId     string                 `protobuf:"bytes,2,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	Authorized    bool                   `protobuf:"varint,3,opt,name=authorized,proto3" json:"authorized,omitempty"`
	AuthCode      string                 `protobuf:"bytes,4,opt,name=auth_code,json=authCode,proto3" json:"auth_code,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AuthorizeResponse) Reset() {
	*x = AuthorizeResponse{}
	mi := &file_proto_demo_payments_v1_payments_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuthorizeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuthorizeResponse) ProtoMessage() {}

func (x *AuthorizeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_demo_payments_v1_payments_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuthorizeResponse.ProtoReflect.Descriptor instead.
func (*AuthorizeResponse) Descriptor() ([]byte, []int) {
	return file_proto_demo_payments_v1_payments_proto_rawDescGZIP(), []int{3}
}

func (x *AuthorizeResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *AuthorizeResponse) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *AuthorizeResponse) GetAuthorized() bool {
	if x != nil {
		return x.Authorized
	}
	return false
}

func (x *AuthorizeResponse) GetAuthCode() string {
	if x != nil {
		return x.AuthCode
	}
	return ""
}

type CaptureRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PaymentId     string                 `protobuf:"bytes,1,opt,name=payment_id,json=paymentId,proto3" json:"payment_id,omitempty"`
	Amount        *Money                 `protobuf:"bytes,2,opt,name=amount,proto3" json:"amount,omitempty"`
	Type          CaptureType            `protobuf:"varint,3,opt,name=type,proto3,enum=demo.payments.v1.CaptureType" json:"type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CaptureRequest) Reset() {
	*x = CaptureRequest{}
	mi := &file_proto_demo_payments_v1_payments_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CaptureRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CaptureRequest) ProtoMessage() {}

func (x *CaptureRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_demo_payments_v1_payments_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CaptureRequest.ProtoReflect.Descriptor instead.
func (*CaptureRequest) Descriptor() ([]byte, []int) {
	return file_proto_demo_payments_v1_payments_proto_rawDescGZIP(), []int{4}
}

func (x *CaptureRequest) GetPaymentId() string {
	if x != nil {
		return x.PaymentId
	}
	return ""
}

func (x *CaptureRequest) GetAmount() *Money {
	if x != nil {
		return x.Amount
	}
	return nil
}

func (x *CaptureRequest) GetType() CaptureType {
	if x != nil {
		return x.Type
	}
	return CaptureType_CAPTURE_TYPE_UNKNOWN
}

type CaptureResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        string                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	RequestId     string                 `protobuf:"bytes,2,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	Captured      bool                   `protobuf:"varint,3,opt,name=captured,proto3" json:"captured,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CaptureResponse) Reset() {
	*x = CaptureResponse{}
	mi := &file_proto_demo_payments_v1_payments_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CaptureResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CaptureResponse) ProtoMessage() {}

func (x *CaptureResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_demo_payments_v1_payments_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CaptureResponse.ProtoReflect.Descriptor instead.
func (*CaptureResponse) Descriptor() ([]byte, []int) {
	return file_proto_demo_payments_v1_payments_proto_rawDescGZIP(), []int{5}
}

func (x *CaptureResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *CaptureResponse) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *CaptureResponse) GetCaptured() bool {
	if x != nil {
		return x.Captured
	}
	return false
}

type RefundDetails struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Reason        string                 `protobuf:"bytes,1,opt,name=reason,proto3" json:"reason,omitempty"`
	ReasonCodes   []string               `protobuf:"bytes,2,rep,name=reason_codes,json=reasonCodes,proto3" json:"reason_codes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RefundDetails) Reset() {
	*x = RefundDetails{}
	mi := &file_proto_demo_payments_v1_payments_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RefundDetails) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RefundDetails) ProtoMessage() {}

func (x *RefundDetails) ProtoReflect() protoreflect.Message {
	mi := &file_proto_demo_payments_v1_payments_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RefundDetails.ProtoReflect.Descriptor instead.
func (*RefundDetails) Descriptor() ([]byte, []int) {
	return file_proto_demo_payments_v1_payments_proto_rawDescGZIP(), []int{6}
}

func (x *RefundDetails) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

func (x *RefundDetails) GetReasonCodes() []string {
	if x != nil {
		return x.ReasonCodes
	}
	return nil
}

type RefundRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PaymentId     string                 `protobuf:"bytes,1,opt,name=payment_id,json=paymentId,proto3" json:"payment_id,omitempty"`
	Amount        *Money                 `protobuf:"bytes,2,opt,name=amount,proto3" json:"amount,omitempty"`
	Details       *RefundDetails         `protobuf:"bytes,3,opt,name=details,proto3" json:"details,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RefundRequest) Reset() {
	*x = RefundRequest{}
	mi := &file_proto_demo_payments_v1_payments_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RefundRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RefundRequest) ProtoMessage() {}

func (x *RefundRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_demo_payments_v1_payments_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RefundRequest.ProtoReflect.Descriptor instead.
func (*RefundRequest) Descriptor() ([]byte, []int) {
	return file_proto_demo_payments_v1_payments_proto_rawDescGZIP(), []int{7}
}

func (x *RefundRequest) GetPaymentId() string {
	if x != nil {
		return x.PaymentId
	}
	return ""
}

func (x *RefundRequest) GetAmount() *Money {
	if x != nil {
		return x.Amount
	}
	return nil
}

func (x *RefundRequest) GetDetails() *RefundDetails {
	if x != nil {
		return x.Details
	}
	return nil
}

type RefundResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        string                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	RequestId     string                 `protobuf:"bytes,2,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	Refunded      bool                   `protobuf:"varint,3,opt,name=refunded,proto3" json:"refunded,omitempty"`
	RefundId      string                 `protobuf:"bytes,4,opt,name=refund_id,json=refundId,proto3" json:"refund_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RefundResponse) Reset() {
	*x = RefundResponse{}
	mi := &file_proto_demo_payments_v1_payments_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RefundResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RefundResponse) ProtoMessage() {}

func (x *RefundResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_demo_payments_v1_payments_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RefundResponse.ProtoReflect.Descriptor instead.
func (*RefundResponse) Descriptor() ([]byte, []int) {
	return file_proto_demo_payments_v1_payments_proto_rawDescGZIP(), []int{8}
}

func (x *RefundResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *RefundResponse) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *RefundResponse) GetRefunded() bool {
	if x != nil {
		return x.Refunded
	}
	return false
}

func (x *RefundResponse) GetRefundId() string {
	if x != nil {
		return x.RefundId
	}
	return ""
}

var File_proto_demo_payments_v1_payments_proto protoreflect.FileDescriptor

const file_proto_demo_payments_v1_payments_proto_rawDesc = "" +
	"\n" +
	"%proto/demo/payments/v1/payments.proto\x12\x10demo.payments.v1\"X\n" +
	"\x05Money\x12\x14\n" +
	"\x05units\x18\x01 \x01(\x03R\x05units\x12\x14\n" +
	"\x05nanos\x18\x02 \x01(\x05R\x05nanos\x12#\n" +
	"\rcurrency_code\x18\x03 \x01(\tR\fcurrencyCode\"|\n" +
	"\x04Card\x12\x1b\n" +
	"\tpan_last4\x18\x01 \x01(\tR\bpanLast4\x12\x1b\n" +
	"\texp_month\x18\x02 \x01(\x05R\bexpMonth\x12\x19\n" +
	"\bexp_year\x18\x03 \x01(\x05R\aexpYear\x12\x1f\n" +
	"\vholder_name\x18\x04 \x01(\tR\n" +
	"holderName\"\xa0\x02\n" +
	"\x10AuthorizeRequest\x12\x1d\n" +
	"\n" +
	"payment_id\x18\x01 \x01(\tR\tpaymentId\x12\x19\n" +
	"\border_id\x18\x02 \x01(\tR\aorderId\x12\x17\n" +
	"\auser_id\x18\x03 \x01(\tR\x06userId\x12/\n" +
	"\x06amount\x18\x04 \x01(\v2\x17.demo.payments.v1.MoneyR\x06amount\x127\n" +
	"\x06method\x18\x05 \x01(\x0e2\x1f.demo.payments.v1.PaymentMethodR\x06method\x12*\n" +
	"\x04card\x18\x06 \x01(\v2\x16.demo.payments.v1.CardR\x04card\x12#\n" +
	"\rmetadata_keys\x18\a \x03(\tR\fmetadataKeys\"\x87\x01\n" +
	"\x11AuthorizeResponse\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\x12\x1d\n" +
	"\n" +
	"request_id\x18\x02 \x01(\tR\trequestId\x12\x1e\n" +
	"\n" +
	"authorized\x18\x03 \x01(\bR\n" +
	"authorized\x12\x1b\n" +
	"\tauth_code\x18\x04 \x01(\tR\bauthCode\"\x93\x01\n" +
	"\x0eCaptureRequest\x12\x1d\n" +
	"\n" +
	"payment_id\x18\x01 \x01(\tR\tpaymentId\x12/\n" +
	"\x06amount\x18\x02 \x01(\v2\x17.demo.payments.v1.MoneyR\x06amount\x121\n" +
	"\x04type\x18\x03 \x01(\x0e2\x1d.demo.payments.v1.CaptureTypeR\x04type\"d\n" +
	"\x0fCaptureResponse\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\x12\x1d\n" +
	"\n" +
	"request_id\x18\x02 \x01(\tR\trequestId\x12\x1a\n" +
	"\bcaptured\x18\x03 \x01(\bR\bcaptured\"J\n" +
	"\rRefundDetails\x12\x16\n" +
	"\x06reason\x18\x01 \x01(\tR\x06reason\x12!\n" +
	"\freason_codes\x18\x02 \x03(\tR\vreasonCodes\"\x9a\x01\n" +
	"\rRefundRequest\x12\x1d\n" +
	"\n" +
	"payment_id\x18\x01 \x01(\tR\tpaymentId\x12/\n" +
	"\x06amount\x18\x02 \x01(\v2\x17.demo.payments.v1.MoneyR\x06amount\x129\n" +
	"\adetails\x18\x03 \x01(\v2\x1f.demo.payments.v1.RefundDetailsR\adetails\"\x80\x01\n" +
	"\x0eRefundResponse\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\x12\x1d\n" +
	"\n" +
	"request_id\x18\x02 \x01(\tR\trequestId\x12\x1a\n" +
	"\brefunded\x18\x03 \x01(\bR\brefunded\x12\x1b\n" +
	"\trefund_id\x18\x04 \x01(\tR\brefundId*u\n" +
	"\rPaymentMethod\x12\x1a\n" +
	"\x16PAYMENT_METHOD_UNKNOWN\x10\x00\x12\x17\n" +
	"\x13PAYMENT_METHOD_CARD\x10\x01\x12\x16\n" +
	"\x12PAYMENT_METHOD_SBP\x10\x02\x12\x17\n" +
	"\x13PAYMENT_METHOD_CASH\x10\x03*X\n" +
	"\vCaptureType\x12\x18\n" +
	"\x14CAPTURE_TYPE_UNKNOWN\x10\x00\x12\x15\n" +
	"\x11CAPTURE_TYPE_FULL\x10\x01\x12\x18\n" +
	"\x14CAPTURE_TYPE_PARTIAL\x10\x022\x84\x02\n" +
	"\x0fPaymentsService\x12T\n" +
	"\tAuthorize\x12\".demo.payments.v1.AuthorizeRequest\x1a#.demo.payments.v1.AuthorizeResponse\x12N\n" +
	"\aCapture\x12 .demo.payments.v1.CaptureRequest\x1a!.demo.payments.v1.CaptureResponse\x12K\n" +
	"\x06Refund\x12\x1f.demo.payments.v1.RefundRequest\x1a .demo.payments.v1.RefundResponseBDZBgithub.com/nikitadada/nil-loader/proto/demo/payments/v1;paymentsv1b\x06proto3"

var (
	file_proto_demo_payments_v1_payments_proto_rawDescOnce sync.Once
	file_proto_demo_payments_v1_payments_proto_rawDescData []byte
)

func file_proto_demo_payments_v1_payments_proto_rawDescGZIP() []byte {
	file_proto_demo_payments_v1_payments_proto_rawDescOnce.Do(func() {
		file_proto_demo_payments_v1_payments_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_demo_payments_v1_payments_proto_rawDesc), len(file_proto_demo_payments_v1_payments_proto_rawDesc)))
	})
	return file_proto_demo_payments_v1_payments_proto_rawDescData
}

var file_proto_demo_payments_v1_payments_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_proto_demo_payments_v1_payments_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_proto_demo_payments_v1_payments_proto_goTypes = []any{
	(PaymentMethod)(0),        // 0: demo.payments.v1.PaymentMethod
	(CaptureType)(0),          // 1: demo.payments.v1.CaptureType
	(*Money)(nil),             // 2: demo.payments.v1.Money
	(*Card)(nil),              // 3: demo.payments.v1.Card
	(*AuthorizeRequest)(nil),  // 4: demo.payments.v1.AuthorizeRequest
	(*AuthorizeResponse)(nil), // 5: demo.payments.v1.AuthorizeResponse
	(*CaptureRequest)(nil),    // 6: demo.payments.v1.CaptureRequest
	(*CaptureResponse)(nil),   // 7: demo.payments.v1.CaptureResponse
	(*RefundDetails)(nil),     // 8: demo.payments.v1.RefundDetails
	(*RefundRequest)(nil),     // 9: demo.payments.v1.RefundRequest
	(*RefundResponse)(nil),    // 10: demo.payments.v1.RefundResponse
}
var file_proto_demo_payments_v1_payments_proto_depIdxs = []int32{
	2,  // 0: demo.payments.v1.AuthorizeRequest.amount:type_name -> demo.payments.v1.Money
	0,  // 1: demo.payments.v1.AuthorizeRequest.method:type_name -> demo.payments.v1.PaymentMethod
	3,  // 2: demo.payments.v1.AuthorizeRequest.card:type_name -> demo.payments.v1.Card
	2,  // 3: demo.payments.v1.CaptureRequest.amount:type_name -> demo.payments.v1.Money
	1,  // 4: demo.payments.v1.CaptureRequest.type:type_name -> demo.payments.v1.CaptureType
	2,  // 5: demo.payments.v1.RefundRequest.amount:type_name -> demo.payments.v1.Money
	8,  // 6: demo.payments.v1.RefundRequest.details:type_name -> demo.payments.v1.RefundDetails
	4,  // 7: demo.payments.v1.PaymentsService.Authorize:input_type -> demo.payments.v1.AuthorizeRequest
	6,  // 8: demo.payments.v1.PaymentsService.Capture:input_type -> demo.payments.v1.CaptureRequest
	9,  // 9: demo.payments.v1.PaymentsService.Refund:input_type -> demo.payments.v1.RefundRequest
	5,  // 10: demo.payments.v1.PaymentsService.Authorize:output_type -> demo.payments.v1.AuthorizeResponse
	7,  // 11: demo.payments.v1.PaymentsService.Capture:output_type -> demo.payments.v1.CaptureResponse
	10, // 12: demo.payments.v1.PaymentsService.Refund:output_type -> demo.payments.v1.RefundResponse
	10, // [10:13] is the sub-list for method output_type
	7,  // [7:10] is the sub-list for method input_type
	7,  // [7:7] is the sub-list for extension type_name
	7,  // [7:7] is the sub-list for extension extendee
	0,  // [0:7] is the sub-list for field type_name
}

func init() { file_proto_demo_payments_v1_payments_proto_init() }
func file_proto_demo_payments_v1_payments_proto_init() {
	if File_proto_demo_payments_v1_payments_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_demo_payments_v1_payments_proto_rawDesc), len(file_proto_demo_payments_v1_payments_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_demo_payments_v1_payments_proto_goTypes,
		DependencyIndexes: file_proto_demo_payments_v1_payments_proto_depIdxs,
		EnumInfos:         file_proto_demo_payments_v1_payments_proto_enumTypes,
		MessageInfos:      file_proto_demo_payments_v1_payments_proto_msgTypes,
	}.Build()
	File_proto_demo_payments_v1_payments_proto = out.File
	file_proto_demo_payments_v1_payments_proto_goTypes = nil
	file_proto_demo_payments_v1_payments_proto_depIdxs = nil
}
