// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.4
// source: proto/demo/user/v1/user.proto

package userv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ProcessUserRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Email         string                 `protobuf:"bytes,3,opt,name=email,proto3" json:"email,omitempty"`
	Phone         string                 `protobuf:"bytes,4,opt,name=phone,proto3" json:"phone,omitempty"`
	Username      string                 `protobuf:"bytes,5,opt,name=username,proto3" json:"username,omitempty"`
	Message       string                 `protobuf:"bytes,6,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProcessUserRequest) Reset() {
	*x = ProcessUserRequest{}
	mi := &file_proto_demo_user_v1_user_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProcessUserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProcessUserRequest) ProtoMessage() {}

func (x *ProcessUserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_demo_user_v1_user_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProcessUserRequest.ProtoReflect.Descriptor instead.
func (*ProcessUserRequest) Descriptor() ([]byte, []int) {
	return file_proto_demo_user_v1_user_proto_rawDescGZIP(), []int{0}
}

func (x *ProcessUserRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *ProcessUserRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ProcessUserRequest) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *ProcessUserRequest) GetPhone() string {
	if x != nil {
		return x.Phone
	}
	return ""
}

func (x *ProcessUserRequest) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *ProcessUserRequest) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type ProcessUserResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        string                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	RequestId     string                 `protobuf:"bytes,2,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	ProcessedAt   int64                  `protobuf:"varint,3,opt,name=processed_at,json=processedAt,proto3" json:"processed_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProcessUserResponse) Reset() {
	*x = ProcessUserResponse{}
	mi := &file_proto_demo_user_v1_user_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProcessUserResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProcessUserResponse) ProtoMessage() {}

func (x *ProcessUserResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_demo_user_v1_user_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProcessUserResponse.ProtoReflect.Descriptor instead.
func (*ProcessUserResponse) Descriptor() ([]byte, []int) {
	return file_proto_demo_user_v1_user_proto_rawDescGZIP(), []int{1}
}

func (x *ProcessUserResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *ProcessUserResponse) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *ProcessUserResponse) GetProcessedAt() int64 {
	if x != nil {
		return x.ProcessedAt
	}
	return 0
}

var File_proto_demo_user_v1_user_proto protoreflect.FileDescriptor

const file_proto_demo_user_v1_user_proto_rawDesc = "" +
	"\n" +
	"\x1dproto/demo/user/v1/user.proto\x12\fdemo.user.v1\"\xa3\x01\n" +
	"\x12ProcessUserRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x14\n" +
	"\x05email\x18\x03 \x01(\tR\x05email\x12\x14\n" +
	"\x05phone\x18\x04 \x01(\tR\x05phone\x12\x1a\n" +
	"\busername\x18\x05 \x01(\tR\busername\x12\x18\n" +
	"\amessage\x18\x06 \x01(\tR\amessage\"o\n" +
	"\x13ProcessUserResponse\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\x12\x1d\n" +
	"\n" +
	"request_id\x18\x02 \x01(\tR\trequestId\x12!\n" +
	"\fprocessed_at\x18\x03 \x01(\x03R\vprocessedAt2a\n" +
	"\vUserService\x12R\n" +
	"\vProcessUser\x12 .demo.user.v1.ProcessUserRequest\x1a!.demo.user.v1.ProcessUserResponseB<Z:github.com/nikitadada/nil-loader/proto/demo/user/v1;userv1b\x06proto3"

var (
	file_proto_demo_user_v1_user_proto_rawDescOnce sync.Once
	file_proto_demo_user_v1_user_proto_rawDescData []byte
)

func file_proto_demo_user_v1_user_proto_rawDescGZIP() []byte {
	file_proto_demo_user_v1_user_proto_rawDescOnce.Do(func() {
		file_proto_demo_user_v1_user_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_demo_user_v1_user_proto_rawDesc), len(file_proto_demo_user_v1_user_proto_rawDesc)))
	})
	return file_proto_demo_user_v1_user_proto_rawDescData
}

var file_proto_demo_user_v1_user_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_proto_demo_user_v1_user_proto_goTypes = []any{
	(*ProcessUserRequest)(nil),  // 0: demo.user.v1.ProcessUserRequest
	(*ProcessUserResponse)(nil), // 1: demo.user.v1.ProcessUserResponse
}
var file_proto_demo_user_v1_user_proto_depIdxs = []int32{
	0, // 0: demo.user.v1.UserService.ProcessUser:input_type -> demo.user.v1.ProcessUserRequest
	1, // 1: demo.user.v1.UserService.ProcessUser:output_type -> demo.user.v1.ProcessUserResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_demo_user_v1_user_proto_init() }
func file_proto_demo_user_v1_user_proto_init() {
	if File_proto_demo_user_v1_user_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_demo_user_v1_user_proto_rawDesc), len(file_proto_demo_user_v1_user_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_demo_user_v1_user_proto_goTypes,
		DependencyIndexes: file_proto_demo_user_v1_user_proto_depIdxs,
		MessageInfos:      file_proto_demo_user_v1_user_proto_msgTypes,
	}.Build()
	File_proto_demo_user_v1_user_proto = out.File
	file_proto_demo_user_v1_user_proto_goTypes = nil
	file_proto_demo_user_v1_user_proto_depIdxs = nil
}
